version: "2"
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: yukpiz
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "33333:3306"